version: "3.8"

services:
  backend:
    build: 
      context: "./java multistage/simpleapi/simpleapi"
    networks: 
      - app-network
    depends_on:
      - database

  database:
    build:
      context: ./ 
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  httpd:
    build:
      context: ./webpage     
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend
  adminer:
    image: adminer
    networks:
      - app-network
    depends_on:
      - database
  

networks:
  app-network:

volumes:
  pgdata:
